apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: fss-vpn-pool
  namespace: metallb-system
spec:
  addresses:
    # Replace with the actual MetalLB IP range for your environment
    - <YOUR_LB_IP>-<YOUR_LB_IP>
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: fss-vpn-pool
  namespace: metallb-system
spec:
  ipAddressPools:
    - fss-vpn-pool
