apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nexus
spec:
  type: NodePort
  selector:
    app: nexus
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30091
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      securityContext:
        fsGroup: 200
      containers:
        - name: nexus
          image: docker.io/edumgt/platform-nexus3:3.90.1-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: INSTALL4J_ADD_VM_PARAMS
              value: -Xms768m -Xmx768m -XX:MaxDirectMemorySize=768m -Djava.util.prefs.userRoot=/nexus-data/javaprefs
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 120
            periodSeconds: 20
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 240
            periodSeconds: 30
            failureThreshold: 10
          resources:
            requests:
              cpu: "250m"
              memory: 1536Mi
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-data
