apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-dataxflow-dev-mongo-data
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: dataxflow-dev
    name: mongo-data-mongodb-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-worker-2
  hostPath:
    path: /var/lib/k8s-data-platform/pv/dataxflow/mongo-data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-dataxflow-dev-teradata-mock-postgres-data
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: dataxflow-dev
    name: teradata-mock-postgres-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-worker-2
  hostPath:
    path: /var/lib/k8s-data-platform/pv/dataxflow/teradata-mock-postgres
    type: DirectoryOrCreate
