apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
type: Opaque
stringData:
  PLATFORM_TERADATA_HOST: teradata-mock-postgres
  PLATFORM_TERADATA_USER: td_mock_user
  PLATFORM_TERADATA_PASSWORD: CHANGE_ME
  PLATFORM_CONTROL_PLANE_USERNAME: platform-admin
  PLATFORM_CONTROL_PLANE_PASSWORD: CHANGE_ME
  PLATFORM_CONTROL_PLANE_SESSION_SECRET: controlplane-session
  PLATFORM_HARBOR_USER: CHANGE_ME
  PLATFORM_HARBOR_PASSWORD: CHANGE_ME
  JUPYTER_TOKEN: CHANGE_ME
  AIRFLOW_ADMIN_USERNAME: airflow
  AIRFLOW_ADMIN_PASSWORD: airflow
  GITLAB_ROOT_PASSWORD: CHANGE_ME
  PLATFORM_NEXUS_ADMIN_PASSWORD: CHANGE_ME
